export 'package:examen_1evaluacion_22/widgets_22/custom_text_form_field_sign_up.dart';
export 'package:examen_1evaluacion_22/widgets_22/custom_text_form_field_sign_in.dart';
export 'package:examen_1evaluacion_22/widgets_22/custom_text_form_field_password_sing_up.dart';
export 'package:examen_1evaluacion_22/widgets_22/custom_text_form_field_password_sign_in.dart';
export 'package:examen_1evaluacion_22/widgets_22/custom_card_tipo_1.dart';